<?php

//https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
return [
    [
        "language" => "Abkhazian",
        "iso2" => "ab",
        "iso3" => "abk",
        "is_active" => false,
    ],
    [
        "language" => "Afar",
        "iso2" => "aa",
        "iso3" => "aar",
        "is_active" => false,
    ],
    [
        "language" => "Afrikaans",
        "iso2" => "af",
        "iso3" => "afr",
        "is_active" => false,
    ],
    [
        "language" => "Akan",
        "iso2" => "ak",
        "iso3" => "aka",
        "is_active" => false,
    ],
    [
        "language" => "Albanian",
        "iso2" => "sq",
        "iso3" => "alb",
        "is_active" => false,
    ],
    [
        "language" => "Amharic",
        "iso2" => "am",
        "iso3" => "amh",
        "is_active" => false,
    ],
    [
        "language" => "Arabic",
        "iso2" => "ar",
        "iso3" => "ara",
        "is_active" => false,
    ],
    [
        "language" => "Aragonese",
        "iso2" => "an",
        "iso3" => "arg",
        "is_active" => false,
    ],
    [
        "language" => "Armenian",
        "iso2" => "hy",
        "iso3" => "arm",
        "is_active" => false,
    ],
    [
        "language" => "Assamese",
        "iso2" => "as",
        "iso3" => "asm",
        "is_active" => false,
    ],
    [
        "language" => "Avaric",
        "iso2" => "av",
        "iso3" => "ava",
        "is_active" => false,
    ],
    [
        "language" => "Avestan",
        "iso2" => "ae",
        "iso3" => "ave",
        "is_active" => false,
    ],
    [
        "language" => "Aymara",
        "iso2" => "ay",
        "iso3" => "aym",
        "is_active" => false,
    ],
    [
        "language" => "Azerbaijani",
        "iso2" => "az",
        "iso3" => "aze",
        "is_active" => false,
    ],
    [
        "language" => "Bambara",
        "iso2" => "bm",
        "iso3" => "bam",
        "is_active" => false,
    ],
    [
        "language" => "Bashkir",
        "iso2" => "ba",
        "iso3" => "bak",
        "is_active" => false,
    ],
    [
        "language" => "Basque",
        "iso2" => "eu",
        "iso3" => "baq",
        "is_active" => false,
    ],
    [
        "language" => "Belarusian",
        "iso2" => "be",
        "iso3" => "bel",
        "is_active" => false,
    ],
    [
        "language" => "Bengali",
        "iso2" => "bn",
        "iso3" => "ben",
        "is_active" => false,
    ],
    [
        "language" => "Bihari languages",
        "iso2" => "bh",
        "iso3" => "bih",
        "is_active" => false,
    ],
    [
        "language" => "Bislama",
        "iso2" => "bi",
        "iso3" => "bis",
        "is_active" => false,
    ],
    [
        "language" => "Bosnian",
        "iso2" => "bs",
        "iso3" => "bos",
        "is_active" => false,
    ],
    [
        "language" => "Breton",
        "iso2" => "br",
        "iso3" => "bre",
        "is_active" => false,
    ],
    [
        "language" => "Bulgarian",
        "iso2" => "bg",
        "iso3" => "bul",
        "is_active" => false,
    ],
    [
        "language" => "Burmese",
        "iso2" => "my",
        "iso3" => "bur",
        "is_active" => false,
    ],
    [
        "language" => "Catalan, Valencian",
        "iso2" => "ca",
        "iso3" => "cat",
        "is_active" => false,
    ],
    [
        "language" => "Chamorro",
        "iso2" => "ch",
        "iso3" => "cha",
        "is_active" => false,
    ],
    [
        "language" => "Chechen",
        "iso2" => "ce",
        "iso3" => "che",
        "is_active" => false,
    ],
    [
        "language" => "Chichewa, Chewa, Nyanja",
        "iso2" => "ny",
        "iso3" => "nya",
        "is_active" => false,
    ],
    [
        "language" => "Chinese",
        "iso2" => "zh",
        "iso3" => "chi",
        "is_active" => false,
    ],
    [
        "language" => "Chuvash",
        "iso2" => "cv",
        "iso3" => "chv",
        "is_active" => false,
    ],
    [
        "language" => "Cornish",
        "iso2" => "kw",
        "iso3" => "cor",
        "is_active" => false,
    ],
    [
        "language" => "Corsican",
        "iso2" => "co",
        "iso3" => "cos",
        "is_active" => false,
    ],
    [
        "language" => "Cree",
        "iso2" => "cr",
        "iso3" => "cre",
        "is_active" => false,
    ],
    [
        "language" => "Croatian",
        "iso2" => "hr",
        "iso3" => "hrv",
        "is_active" => false,
    ],
    [
        "language" => "Czech",
        "iso2" => "cs",
        "iso3" => "cze",
        "is_active" => false,
    ],
    [
        "language" => "Danish",
        "iso2" => "da",
        "iso3" => "dan",
        "is_active" => true,
    ],
    [
        "language" => "Divehi, Dhivehi, Maldivian",
        "iso2" => "dv",
        "iso3" => "div",
        "is_active" => false,
    ],
    [
        "language" => "Dutch, Flemish",
        "iso2" => "nl",
        "iso3" => "dut",
        "is_active" => false,
    ],
    [
        "language" => "Dzongkha",
        "iso2" => "dz",
        "iso3" => "dzo",
        "is_active" => false,
    ],
    [
        "language" => "English",
        "iso2" => "en",
        "iso3" => "eng",
        "is_active" => true,
    ],
    [
        "language" => "Esperanto",
        "iso2" => "eo",
        "iso3" => "epo",
        "is_active" => false,
    ],
    [
        "language" => "Estonian",
        "iso2" => "et",
        "iso3" => "est",
        "is_active" => false,
    ],
    [
        "language" => "Ewe",
        "iso2" => "ee",
        "iso3" => "ewe",
        "is_active" => false,
    ],
    [
        "language" => "Faroese",
        "iso2" => "fo",
        "iso3" => "fao",
        "is_active" => false,
    ],
    [
        "language" => "Fijian",
        "iso2" => "fj",
        "iso3" => "fij",
        "is_active" => false,
    ],
    [
        "language" => "Finnish",
        "iso2" => "fi",
        "iso3" => "fin",
        "is_active" => false,
    ],
    [
        "language" => "French",
        "iso2" => "fr",
        "iso3" => "fre",
        "is_active" => true,
    ],
    [
        "language" => "Fulah",
        "iso2" => "ff",
        "iso3" => "ful",
        "is_active" => false,
    ],
    [
        "language" => "Galician",
        "iso2" => "gl",
        "iso3" => "glg",
        "is_active" => false,
    ],
    [
        "language" => "Georgian",
        "iso2" => "ka",
        "iso3" => "geo",
        "is_active" => false,
    ],
    [
        "language" => "German",
        "iso2" => "de",
        "iso3" => "ger",
        "is_active" => true,
    ],
    [
        "language" => "Greek, Modern (1453-)",
        "iso2" => "el",
        "iso3" => "gre",
        "is_active" => false,
    ],
    [
        "language" => "Guarani",
        "iso2" => "gn",
        "iso3" => "grn",
        "is_active" => false,
    ],
    [
        "language" => "Gujarati",
        "iso2" => "gu",
        "iso3" => "guj",
        "is_active" => false,
    ],
    [
        "language" => "Haitian, Haitian Creole",
        "iso2" => "ht",
        "iso3" => "hat",
        "is_active" => false,
    ],
    [
        "language" => "Hausa",
        "iso2" => "ha",
        "iso3" => "hau",
        "is_active" => false,
    ],
    [
        "language" => "Hebrew",
        "iso2" => "he",
        "iso3" => "heb",
        "is_active" => false,
    ],
    [
        "language" => "Herero",
        "iso2" => "hz",
        "iso3" => "her",
        "is_active" => false,
    ],
    [
        "language" => "Hindi",
        "iso2" => "hi",
        "iso3" => "hin",
        "is_active" => false,
    ],
    [
        "language" => "Hiri Motu",
        "iso2" => "ho",
        "iso3" => "hmo",
        "is_active" => false,
    ],
    [
        "language" => "Hungarian",
        "iso2" => "hu",
        "iso3" => "hun",
        "is_active" => false,
    ],
    [
        "language" => "Interlingua (International Auxiliary Language Association)",
        "iso2" => "ia",
        "iso3" => "ina",
        "is_active" => false,
    ],
    [
        "language" => "Indonesian",
        "iso2" => "id",
        "iso3" => "ind",
        "is_active" => false,
    ],
    [
        "language" => "Interlingue, Occidental",
        "iso2" => "ie",
        "iso3" => "ile",
        "is_active" => false,
    ],
    [
        "language" => "Irish",
        "iso2" => "ga",
        "iso3" => "gle",
        "is_active" => false,
    ],
    [
        "language" => "Igbo",
        "iso2" => "ig",
        "iso3" => "ibo",
        "is_active" => false,
    ],
    [
        "language" => "Inupiaq",
        "iso2" => "ik",
        "iso3" => "ipk",
        "is_active" => false,
    ],
    [
        "language" => "Ido",
        "iso2" => "io",
        "iso3" => "ido",
        "is_active" => false,
    ],
    [
        "language" => "Icelandic",
        "iso2" => "is",
        "iso3" => "ice",
        "is_active" => false,
    ],
    [
        "language" => "Italian",
        "iso2" => "it",
        "iso3" => "ita",
        "is_active" => true,
    ],
    [
        "language" => "Inuktitut",
        "iso2" => "iu",
        "iso3" => "iku",
        "is_active" => false,
    ],
    [
        "language" => "Japanese",
        "iso2" => "ja",
        "iso3" => "jpn",
        "is_active" => false,
    ],
    [
        "language" => "Javanese",
        "iso2" => "jv",
        "iso3" => "jav",
        "is_active" => false,
    ],
    [
        "language" => "Kalaallisut, Greenlandic",
        "iso2" => "kl",
        "iso3" => "kal",
        "is_active" => false,
    ],
    [
        "language" => "Kannada",
        "iso2" => "kn",
        "iso3" => "kan",
        "is_active" => false,
    ],
    [
        "language" => "Kanuri",
        "iso2" => "kr",
        "iso3" => "kau",
        "is_active" => false,
    ],
    [
        "language" => "Kashmiri",
        "iso2" => "ks",
        "iso3" => "kas",
        "is_active" => false,
    ],
    [
        "language" => "Kazakh",
        "iso2" => "kk",
        "iso3" => "kaz",
        "is_active" => false,
    ],
    [
        "language" => "Central Khmer",
        "iso2" => "km",
        "iso3" => "khm",
        "is_active" => false,
    ],
    [
        "language" => "Kikuyu, Gikuyu",
        "iso2" => "ki",
        "iso3" => "kik",
        "is_active" => false,
    ],
    [
        "language" => "Kinyarwanda",
        "iso2" => "rw",
        "iso3" => "kin",
        "is_active" => false,
    ],
    [
        "language" => "Kirghiz, Kyrgyz",
        "iso2" => "ky",
        "iso3" => "kir",
        "is_active" => false,
    ],
    [
        "language" => "Komi",
        "iso2" => "kv",
        "iso3" => "kom",
        "is_active" => false,
    ],
    [
        "language" => "Kongo",
        "iso2" => "kg",
        "iso3" => "kon",
        "is_active" => false,
    ],
    [
        "language" => "Korean",
        "iso2" => "ko",
        "iso3" => "kor",
        "is_active" => false,
    ],
    [
        "language" => "Kurdish",
        "iso2" => "ku",
        "iso3" => "kur",
        "is_active" => false,
    ],
    [
        "language" => "Kuanyama, Kwanyama",
        "iso2" => "kj",
        "iso3" => "kua",
        "is_active" => false,
    ],
    [
        "language" => "Latin",
        "iso2" => "la",
        "iso3" => "lat",
        "is_active" => false,
    ],
    [
        "language" => "Luxembourgish, Letzeburgesch",
        "iso2" => "lb",
        "iso3" => "ltz",
        "is_active" => false,
    ],
    [
        "language" => "Ganda",
        "iso2" => "lg",
        "iso3" => "lug",
        "is_active" => false,
    ],
    [
        "language" => "Limburgan, Limburger, Limburgish",
        "iso2" => "li",
        "iso3" => "lim",
        "is_active" => false,
    ],
    [
        "language" => "Lingala",
        "iso2" => "ln",
        "iso3" => "lin",
        "is_active" => false,
    ],
    [
        "language" => "Lao",
        "iso2" => "lo",
        "iso3" => "lao",
        "is_active" => false,
    ],
    [
        "language" => "Lithuanian",
        "iso2" => "lt",
        "iso3" => "lit",
        "is_active" => false,
    ],
    [
        "language" => "Luba-Katanga",
        "iso2" => "lu",
        "iso3" => "lub",
        "is_active" => false,
    ],
    [
        "language" => "Latvian",
        "iso2" => "lv",
        "iso3" => "lav",
        "is_active" => false,
    ],
    [
        "language" => "Manx",
        "iso2" => "gv",
        "iso3" => "glv",
        "is_active" => false,
    ],
    [
        "language" => "Macedonian",
        "iso2" => "mk",
        "iso3" => "mac",
        "is_active" => false,
    ],
    [
        "language" => "Malagasy",
        "iso2" => "mg",
        "iso3" => "mlg",
        "is_active" => false,
    ],
    [
        "language" => "Malay",
        "iso2" => "ms",
        "iso3" => "may",
        "is_active" => false,
    ],
    [
        "language" => "Malayalam",
        "iso2" => "ml",
        "iso3" => "mal",
        "is_active" => false,
    ],
    [
        "language" => "Maltese",
        "iso2" => "mt",
        "iso3" => "mlt",
        "is_active" => false,
    ],
    [
        "language" => "Maori",
        "iso2" => "mi",
        "iso3" => "mao",
        "is_active" => false,
    ],
    [
        "language" => "Marathi",
        "iso2" => "mr",
        "iso3" => "mar",
        "is_active" => false,
    ],
    [
        "language" => "Marshallese",
        "iso2" => "mh",
        "iso3" => "mah",
        "is_active" => false,
    ],
    [
        "language" => "Mongolian",
        "iso2" => "mn",
        "iso3" => "mon",
        "is_active" => false,
    ],
    [
        "language" => "Nauru",
        "iso2" => "na",
        "iso3" => "nau",
        "is_active" => false,
    ],
    [
        "language" => "Navajo, Navaho",
        "iso2" => "nv",
        "iso3" => "nav",
        "is_active" => false,
    ],
    [
        "language" => "North Ndebele",
        "iso2" => "nd",
        "iso3" => "nde",
        "is_active" => false,
    ],
    [
        "language" => "Nepali",
        "iso2" => "ne",
        "iso3" => "nep",
        "is_active" => false,
    ],
    [
        "language" => "Ndonga",
        "iso2" => "ng",
        "iso3" => "ndo",
        "is_active" => false,
    ],
    [
        "language" => "Norwegian BokmÃ¥l",
        "iso2" => "nb",
        "iso3" => "nob",
        "is_active" => false,
    ],
    [
        "language" => "Norwegian Nynorsk",
        "iso2" => "nn",
        "iso3" => "nno",
        "is_active" => false,
    ],
    [
        "language" => "Norwegian",
        "iso2" => "no",
        "iso3" => "nor",
        "is_active" => true,
    ],
    [
        "language" => "Sichuan Yi, Nuosu",
        "iso2" => "ii",
        "iso3" => "iii",
        "is_active" => false,
    ],
    [
        "language" => "South Ndebele",
        "iso2" => "nr",
        "iso3" => "nbl",
        "is_active" => false,
    ],
    [
        "language" => "Occitan",
        "iso2" => "oc",
        "iso3" => "oci",
        "is_active" => false,
    ],
    [
        "language" => "Ojibwa",
        "iso2" => "oj",
        "iso3" => "oji",
        "is_active" => false,
    ],
    [
        "language" => "Church Slavic, Old Slavonic, Church Slavonic, Old Bulgarian, Old Church Slavonic",
        "iso2" => "cu",
        "iso3" => "chu",
        "is_active" => false,
    ],
    [
        "language" => "Oromo",
        "iso2" => "om",
        "iso3" => "orm",
        "is_active" => false,
    ],
    [
        "language" => "Oriya",
        "iso2" => "or",
        "iso3" => "ori",
        "is_active" => false,
    ],
    [
        "language" => "Ossetian, Ossetic",
        "iso2" => "os",
        "iso3" => "oss",
        "is_active" => false,
    ],
    [
        "language" => "Punjabi, Panjabi",
        "iso2" => "pa",
        "iso3" => "pan",
        "is_active" => false,
    ],
    [
        "language" => "Pali",
        "iso2" => "pi",
        "iso3" => "pli",
        "is_active" => false,
    ],
    [
        "language" => "Persian",
        "iso2" => "fa",
        "iso3" => "per",
        "is_active" => false,
    ],
    [
        "language" => "Polish",
        "iso2" => "pl",
        "iso3" => "pol",
        "is_active" => false,
    ],
    [
        "language" => "Pashto, Pushto",
        "iso2" => "ps",
        "iso3" => "pus",
        "is_active" => false,
    ],
    [
        "language" => "Portuguese",
        "iso2" => "pt",
        "iso3" => "por",
        "is_active" => false,
    ],
    [
        "language" => "Quechua",
        "iso2" => "qu",
        "iso3" => "que",
        "is_active" => false,
    ],
    [
        "language" => "Romansh",
        "iso2" => "rm",
        "iso3" => "roh",
        "is_active" => false,
    ],
    [
        "language" => "Rundi",
        "iso2" => "rn",
        "iso3" => "run",
        "is_active" => false,
    ],
    [
        "language" => "Romanian, Moldavian, Moldovan",
        "iso2" => "ro",
        "iso3" => "rum",
        "is_active" => false,
    ],
    [
        "language" => "Russian",
        "iso2" => "ru",
        "iso3" => "rus",
        "is_active" => false,
    ],
    [
        "language" => "Sanskrit",
        "iso2" => "sa",
        "iso3" => "san",
        "is_active" => false,
    ],
    [
        "language" => "Sardinian",
        "iso2" => "sc",
        "iso3" => "srd",
        "is_active" => false,
    ],
    [
        "language" => "Sindhi",
        "iso2" => "sd",
        "iso3" => "snd",
        "is_active" => false,
    ],
    [
        "language" => "Northern Sami",
        "iso2" => "se",
        "iso3" => "sme",
        "is_active" => false,
    ],
    [
        "language" => "Samoan",
        "iso2" => "sm",
        "iso3" => "smo",
        "is_active" => false,
    ],
    [
        "language" => "Sango",
        "iso2" => "sg",
        "iso3" => "sag",
        "is_active" => false,
    ],
    [
        "language" => "Serbian",
        "iso2" => "sr",
        "iso3" => "srp",
        "is_active" => false,
    ],
    [
        "language" => "Gaelic, Scottish Gaelic",
        "iso2" => "gd",
        "iso3" => "gla",
        "is_active" => false,
    ],
    [
        "language" => "Shona",
        "iso2" => "sn",
        "iso3" => "sna",
        "is_active" => false,
    ],
    [
        "language" => "Sinhala, Sinhalese",
        "iso2" => "si",
        "iso3" => "sin",
        "is_active" => false,
    ],
    [
        "language" => "Slovak",
        "iso2" => "sk",
        "iso3" => "slo",
        "is_active" => false,
    ],
    [
        "language" => "Slovenian",
        "iso2" => "sl",
        "iso3" => "slv",
        "is_active" => false,
    ],
    [
        "language" => "Somali",
        "iso2" => "so",
        "iso3" => "som",
        "is_active" => false,
    ],
    [
        "language" => "Southern Sotho",
        "iso2" => "st",
        "iso3" => "sot",
        "is_active" => false,
    ],
    [
        "language" => "Spanish, Castilian",
        "iso2" => "es",
        "iso3" => "spa",
        "is_active" => true,
    ],
    [
        "language" => "Sundanese",
        "iso2" => "su",
        "iso3" => "sun",
        "is_active" => false,
    ],
    [
        "language" => "Swahili",
        "iso2" => "sw",
        "iso3" => "swa",
        "is_active" => false,
    ],
    [
        "language" => "Swati",
        "iso2" => "ss",
        "iso3" => "ssw",
        "is_active" => false,
    ],
    [
        "language" => "Swedish",
        "iso2" => "sv",
        "iso3" => "swe",
        "is_active" => true,
    ],
    [
        "language" => "Tamil",
        "iso2" => "ta",
        "iso3" => "tam",
        "is_active" => false,
    ],
    [
        "language" => "Telugu",
        "iso2" => "te",
        "iso3" => "tel",
        "is_active" => false,
    ],
    [
        "language" => "Tajik",
        "iso2" => "tg",
        "iso3" => "tgk",
        "is_active" => false,
    ],
    [
        "language" => "Thai",
        "iso2" => "th",
        "iso3" => "tha",
        "is_active" => false,
    ],
    [
        "language" => "Tigrinya",
        "iso2" => "ti",
        "iso3" => "tir",
        "is_active" => false,
    ],
    [
        "language" => "Tibetan",
        "iso2" => "bo",
        "iso3" => "tib",
        "is_active" => false,
    ],
    [
        "language" => "Turkmen",
        "iso2" => "tk",
        "iso3" => "tuk",
        "is_active" => false,
    ],
    [
        "language" => "Tagalog",
        "iso2" => "tl",
        "iso3" => "tgl",
        "is_active" => false,
    ],
    [
        "language" => "Tswana",
        "iso2" => "tn",
        "iso3" => "tsn",
        "is_active" => false,
    ],
    [
        "language" => "Tonga (Tonga Islands)",
        "iso2" => "to",
        "iso3" => "ton",
        "is_active" => false,
    ],
    [
        "language" => "Turkish",
        "iso2" => "tr",
        "iso3" => "tur",
        "is_active" => false,
    ],
    [
        "language" => "Tsonga",
        "iso2" => "ts",
        "iso3" => "tso",
        "is_active" => false,
    ],
    [
        "language" => "Tatar",
        "iso2" => "tt",
        "iso3" => "tat",
        "is_active" => false,
    ],
    [
        "language" => "Twi",
        "iso2" => "tw",
        "iso3" => "twi",
        "is_active" => false,
    ],
    [
        "language" => "Tahitian",
        "iso2" => "ty",
        "iso3" => "tah",
        "is_active" => false,
    ],
    [
        "language" => "Uighur, Uyghur",
        "iso2" => "ug",
        "iso3" => "uig",
        "is_active" => false,
    ],
    [
        "language" => "Ukrainian",
        "iso2" => "uk",
        "iso3" => "ukr",
        "is_active" => false,
    ],
    [
        "language" => "Urdu",
        "iso2" => "ur",
        "iso3" => "urd",
        "is_active" => false,
    ],
    [
        "language" => "Uzbek",
        "iso2" => "uz",
        "iso3" => "uzb",
        "is_active" => false,
    ],
    [
        "language" => "Venda",
        "iso2" => "ve",
        "iso3" => "ven",
        "is_active" => false,
    ],
    [
        "language" => "Vietnamese",
        "iso2" => "vi",
        "iso3" => "vie",
        "is_active" => false,
    ],
    [
        "language" => "VolapÃ¼k",
        "iso2" => "vo",
        "iso3" => "vol",
        "is_active" => false,
    ],
    [
        "language" => "Walloon",
        "iso2" => "wa",
        "iso3" => "wln",
        "is_active" => false,
    ],
    [
        "language" => "Welsh",
        "iso2" => "cy",
        "iso3" => "wel",
        "is_active" => false,
    ],
    [
        "language" => "Wolof",
        "iso2" => "wo",
        "iso3" => "wol",
        "is_active" => false,
    ],
    [
        "language" => "Western Frisian",
        "iso2" => "fy",
        "iso3" => "fry",
        "is_active" => false,
    ],
    [
        "language" => "Xhosa",
        "iso2" => "xh",
        "iso3" => "xho",
        "is_active" => false,
    ],
    [
        "language" => "Yiddish",
        "iso2" => "yi",
        "iso3" => "yid",
        "is_active" => false,
    ],
    [
        "language" => "Yoruba",
        "iso2" => "yo",
        "iso3" => "yor",
        "is_active" => false,
    ],
    [
        "language" => "Zhuang, Chuang",
        "iso2" => "za",
        "iso3" => "zha",
        "is_active" => false,
    ],
    [
        "language" => "Zulu",
        "iso2" => "zu",
        "iso3" => "zul",
        "is_active" => false,
    ],
];